---
wordpress_version: latest

wordpress_install_dir: /var/www

wordpress_download_url: "https://wordpress.org/{{ wordpress_version }}.tar.gz"

wordpress_archive: /tmp/wordpress.tar.gz

wordpress_extract_dir: /tmp
