---
- name: Install Apache
  ansible.builtin.apt:
    name: apache2
    state: present

- name: Enable Apache service
  ansible.builtin.service:
    name: apache2
    enabled: true
    state: started

- name: Configure VirtualHost
  ansible.builtin.import_tasks: vhost.yml

- name: Configure Apache security
  ansible.builtin.import_tasks: hardening.yml

- name: Configure security headers
  ansible.builtin.import_tasks: headers.yml
