---
- name: Create Apache VirtualHost
  ansible.builtin.template:
    src: wordpress.conf.j2
    dest: /etc/apache2/sites-available/wordpress.conf
    owner: root
    group: root
    mode: "0644"

- name: Enable rewrite module
  ansible.builtin.command: a2enmod rewrite
  register: apache_rewrite_result
  changed_when: "'already enabled' not in apache_rewrite_result.stdout"

- name: Check default site
  ansible.builtin.stat:
    path: /etc/apache2/sites-enabled/000-default.conf
  register: apache_default_site

- name: Disable default site
  ansible.builtin.command:
    cmd: a2dissite 000-default.conf
  when: apache_default_site.stat.exists
  changed_when: apache_default_site.stat.exists
  notify: Reload Apache

- name: Check WordPress site
  ansible.builtin.stat:
    path: /etc/apache2/sites-enabled/wordpress.conf
  register: apache_wordpress_site

- name: Enable WordPress site
  ansible.builtin.command:
    cmd: a2ensite wordpress.conf
  when: not apache_wordpress_site.stat.exists
  changed_when: not apache_wordpress_site.stat.exists
  notify: Reload Apache
