---
- name: Download WordPress
  ansible.builtin.import_tasks: download.yml

- name: Configure WordPress
  ansible.builtin.import_tasks: config.yml

- name: Configure permissions
  ansible.builtin.import_tasks: permissions.yml
