---
- name: Install OpenSSH server
  ansible.builtin.apt:
    name: openssh-server
    state: present

- name: Disable root login
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PermitRootLogin'
    line: 'PermitRootLogin {{ ssh_permit_root_login }}'
    backup: true
    validate: '/usr/sbin/sshd -t -f %s'
  notify: Restart ssh

- name: Disable password authentication
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PasswordAuthentication'
    line: 'PasswordAuthentication {{ ssh_password_authentication }}'
    backup: true
    validate: '/usr/sbin/sshd -t -f %s'
  notify: Restart ssh

- name: Enable public key authentication
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PubkeyAuthentication'
    line: 'PubkeyAuthentication {{ ssh_pubkey_authentication }}'
    backup: true
    validate: '/usr/sbin/sshd -t -f %s'
  notify: Restart ssh
