---
- name: Install UFW
  ansible.builtin.apt:
    name: ufw
    state: present

- name: Allow required TCP ports
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop: "{{ firewall_allowed_tcp_ports }}"

- name: Enable UFW
  community.general.ufw:
    state: enabled
