---
- name: Create jail.local
  ansible.builtin.template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: "0644"
  notify: Restart Fail2ban

- name: Enable Fail2ban
  ansible.builtin.service:
    name: fail2ban
    enabled: true
    state: started
